import Vue from 'vue'

Vue.component('IconUser', require('./user').default)
Vue.component('IconKey', require('./key').default)
Vue.component('IconHome', require('./home').default)
Vue.component('IconCall', require('./call').default)
Vue.component('IconTerminals', require('./terminals').default)
Vue.component('IconUsers', require('./users').default)
Vue.component('IconStat', require('./stat').default)
Vue.component('IconSettings', require('./settings').default)
Vue.component('IconMicroOn', require('./micro-on').default)
Vue.component('IconMicroOff', require('./micro-off').default)
Vue.component('IconCameraOn', require('./camera-on').default)
Vue.component('IconCameraOff', require('./camera-off').default)
Vue.component('IconComment', require('./comment').default)
Vue.component('IconBack', require('./back').default)
Vue.component('IconStar', require('./star').default)
Vue.component('IconDots', require('./dots').default)
Vue.component('IconRubbishBin', require('./rubbish-bin').default)
Vue.component('IconLighting', require('./lighting').default)
Vue.component('IconHeart', require('./heart').default)
Vue.component('IconArrowLeft', require('./arrow-left').default)
Vue.component('IconArrowRight', require('./arrow-right').default)
Vue.component('IconUs', require('./us').default)
