import Vue from 'vue'

Vue.component('UiInput', require('./input').default)
Vue.component('UiBtn', require('./btn').default)
Vue.component('UiCheckbox', require('./checkbox').default)
Vue.component('UiLink', require('./link').default)
Vue.component('UiToggle', require('./toggle').default)
Vue.component('UiBadge', require('./badge').default)
Vue.component('UiPreloader', require('./preloader').default)
Vue.component('UiInputPeriod', require('./input-period').default)
Vue.component('UiSelect', require('./select').default)
Vue.component('UiProgress', require('./progress').default)
Vue.component('UiArrow', require('./arrow').default)
Vue.component('UiCheckboxGroup', require('./checkbox-group').default)
Vue.component('UiStars', require('./stars').default)
Vue.component('UiPassiveAbility', require('./passive-ability').default)
Vue.component('UiCoin', require('./coin').default)
Vue.component('UiLives', require('./lives').default)
Vue.component('UiSpaceship', require('./spaceship').default)
Vue.component('UiPlayerCard', require('./player-card').default)
